---
- name: Check OS
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] == "7"
    fail_msg: Host {{ ansible_hostname }} does not meet minimal reqs

- name: Pretasks
  ansible.builtin.include_tasks: pretasks.yml
  tags: [always]

- name: Yum
  ansible.builtin.include_tasks: yum.yml
  tags: [always]

- name: MySQL secure installation
  ansible.builtin.include_tasks: mysql_secure_install.yml
  tags: [always]

- name: Configure master
  ansible.builtin.include_tasks: mysql_master.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- name: Configure slave
  ansible.builtin.include_tasks: mysql_slave.yml
  when:
    inventory_hostname == "db02"
  tags: [always]

- name: Wordpress DB
  ansible.builtin.include_tasks: mysql_wordpress.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- name: Node Exporter
  ansible.builtin.include_tasks: exporter.yml
  tags: [always]

- name: Mysql Node Exporter
  ansible.builtin.include_tasks: mysqld_exporter.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- name: Grafana
  ansible.builtin.include_tasks: mysql_grafana.yml
  when:
    inventory_hostname == "db01"
  tags: [always]
...
