---

- name: Check OS
  assert:
    that:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
    fail_msg: Host {{ ansible_hostname }} does not meet minimal reqs

- include_tasks: pretasks.yml
  tags: [always]

- include_tasks: yum.yml
  tags: [always]

- include_tasks: mysql_secure_install.yml
  tags: [always]

- include_tasks: mysql_master.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- include_tasks: mysql_slave.yml
  when:
    inventory_hostname == "db02"
  tags: [always]

- include_tasks: mysql_wordpress.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- include_tasks: exporter.yml
  tags: [always]

- include_tasks: mysqld_exporter.yml
  when:
    inventory_hostname == "db01"
  tags: [always]

- include_tasks: mysql_grafana.yml
  when:
    inventory_hostname == "db01"
  tags: [always]
