---
- name: Slave - Check my.cnf file
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ cnf_path }}/my.cnf"
    line: "server-id = 2"
  check_mode: true
  register: config
  tags:
    - mysql
    - slave

- name: Slave - Copy my.cnf on Slave
  become: true
  ansible.builtin.template:
    src: slave_my.cnf.j2
    dest: "{{ cnf_path }}/my.cnf"
    mode: '0644'
  when: config.changed
  notify:
    - Restart MySQL
  tags:
    - mysql
    - slave

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Slave - Get data from master file and position
  community.mysql.mysql_replication:
    login_user: root
    login_password: "{{ root_password }}"
    login_host: localhost
    mode: getmaster
  register: master_data
  tags:
    - mysql
    - slave

- name: Slave configuration
  block:

    - name: Slave - Config slave
      community.mysql.mysql_replication:
        login_user: root
        login_password: "{{ root_password }}"
        login_host: localhost
        mode: changemaster
        master_host: "{{ primary_host }}"
        master_user: "{{ replica_user }}"
        master_password: "{{ replica_pass }}"
        master_log_file: "{{ master_data.File }}"
        master_log_pos: "{{ master_data.Position }}"
      register: result
      failed_when: result.msg == -1
      tags:
        - mysql
        - slave

  rescue:

    - name: Slave - Config slave
      community.mysql.mysql_replication:
        login_user: root
        login_password: "{{ root_password }}"
        login_host: localhost
        mode: changemaster
        master_host: "{{ primary_host }}"
        master_user: "{{ replica_user }}"
        master_password: "{{ replica_pass }}"
        master_log_file: "{{ master_data.File }}"
        master_log_pos: "{{ master_data.Position }}"
      tags:
        - mysql
        - slave

- name: Slave - Start slave
  community.mysql.mysql_replication:
    login_user: root
    login_password: "{{ root_password }}"
    login_host: localhost
    mode: startslave
  tags:
    - mysql
    - slave
...
